version: "3"

services:
    # Database
    db:
        image: mysql:5.7
        container_name: dbwp
        volumes:
            - ./db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        networks:
            - wpsite
    # phpmyadmin
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: user
            PMA_PASSWORD: password
        networks:
            - wpsite
    # Wordpress
    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        container_name: wp
        ports:
            - "8080:80"
        restart: always
        volumes:
            - ./wp_data:/var/www/html
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: user
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_DB_NAME: db
        networks:
            - wpsite
networks:
    wpsite:
volumes:
    db_data:
